from app.models import db, Direction

def seed_directions():
    seedArray = []

    seedArray.append(Direction(step_number=1, instruction="Melt butter.", recipe_id=1))
    seedArray.append(Direction(step_number=2, instruction="Add sugar and molasses.", recipe_id=1))
    seedArray.append(Direction(step_number=3, instruction="Mix in eggs.", recipe_id=1))
    seedArray.append(Direction(step_number=4, instruction="Mix baking soda and water together, then add to mixture.", recipe_id=1))
    seedArray.append(Direction(step_number=5, instruction="Stir in dry ingredients (flour, spices, baking powder).", recipe_id=1))
    seedArray.append(Direction(step_number=6, instruction="Refrigerate overnight.", recipe_id=1))
    seedArray.append(Direction(step_number=7, instruction="Roll on floured board and cut.", recipe_id=1))
    seedArray.append(Direction(step_number=8, instruction="Bake at 350F for 7-8 minutes.", recipe_id=1))
    seedArray.append(Direction(step_number=1, instruction="Mix melted butter and brown sugar.", recipe_id=2))
    seedArray.append(Direction(step_number=2, instruction="Add eggs and vanilla, mix well.", recipe_id=2))
    seedArray.append(Direction(step_number=3, instruction="Add dry ingredients, then add chocolate chips and mix.", recipe_id=2))
    seedArray.append(Direction(step_number=4, instruction="Scoop onto greased cookie sheet ", recipe_id=2))
    seedArray.append(Direction(step_number=5, instruction="Bake at 335F (convection) for 7 minutes. Don't overbake.", recipe_id=2))
    seedArray.append(Direction(step_number=1, instruction="Lightly oil a shallow 9x13 glass dish and put ingredients in the dish as listed, in order.", recipe_id=3))
    seedArray.append(Direction(step_number=2, instruction="Chill and serve.", recipe_id=3))
    seedArray.append(Direction(step_number=1, instruction="Heat over to 400F.", recipe_id=4))
    seedArray.append(Direction(step_number=2, instruction="Grease muffin tins, or put in paper baking cups.", recipe_id=4))
    seedArray.append(Direction(step_number=3, instruction="Beat egg; stir in milk, oil, and blueberries.", recipe_id=4))
    seedArray.append(Direction(step_number=4, instruction="Stir in remaining ingredients all at once, just until flour is moistened (batter will be lumpy).", recipe_id=4))
    seedArray.append(Direction(step_number=5, instruction="Fill muffin cups.", recipe_id=4))
    seedArray.append(Direction(step_number=6, instruction="Bake until golden brown, about 20 min.", recipe_id=4))
    seedArray.append(Direction(step_number=7, instruction="Remove from pan.", recipe_id=4))
    seedArray.append(Direction(step_number=1, instruction="Cut bacon into cubes. Drain fat into heavy saucepan", recipe_id=5))
    seedArray.append(Direction(step_number=2, instruction="Add onions and let simmer until transparent.", recipe_id=5))
    seedArray.append(Direction(step_number=3, instruction="Add water and potatoes. Simmer until potatoes are tender.", recipe_id=5))
    seedArray.append(Direction(step_number=4, instruction="Add rest of ingredients. Heat thoroughly, but do not boil.", recipe_id=5))
    seedArray.append(Direction(step_number=1, instruction="Pare apples; cut into eighths", recipe_id=6))
    seedArray.append(Direction(step_number=2, instruction="Arrange in unbaked pie shell.", recipe_id=6))
    seedArray.append(Direction(step_number=3, instruction="Mix .5 cup sugar with the cinnamon; sprinkle over apples.", recipe_id=6))
    seedArray.append(Direction(step_number=4, instruction="Mix .5 sugar with the flour; cut in butter until crumbly and sprinkle over apples.", recipe_id=6))
    seedArray.append(Direction(step_number=5, instruction="Bake in hot oven (400F) for 40 minutes or until done.", recipe_id=6))
    seedArray.append(Direction(step_number=6, instruction="Cool. Spoon whipped cream atop; sprinkle with cinnamon sugar mixture.", recipe_id=6))
    seedArray.append(Direction(step_number=1, instruction="Mix all ingredients in a huge mixing bowl.", recipe_id=7))
    seedArray.append(Direction(step_number=2, instruction="Place in greased glass baking dishes; makes two 13x9x2 pans.", recipe_id=7))
    seedArray.append(Direction(step_number=3, instruction="Bake at 350F for 25 minutes or until onions are soft and dip is bubbly and browned.", recipe_id=7))
    seedArray.append(Direction(step_number=4, instruction="Serve warm with sturdy tortilla chips.", recipe_id=7))
    seedArray.append(Direction(step_number=1, instruction="In a large bowl, combine pudding mix with crushed pineapple. Mix with a wooden spoon until pudding mix is blended with pineapple liquids.", recipe_id=8))
    seedArray.append(Direction(step_number=2, instruction="Add in Cool Whip and mini marshmallows. ", recipe_id=8))
    seedArray.append(Direction(step_number=3, instruction="Cover and refrigerate four hours, or overnight. ", recipe_id=8))
    seedArray.append(Direction(step_number=4, instruction="Serve with maraschino cherries as a garnish.", recipe_id=8))
    seedArray.append(Direction(step_number=1, instruction="Combine all.", recipe_id=9))
    seedArray.append(Direction(step_number=2, instruction="Fry in oil.", recipe_id=9))
    seedArray.append(Direction(step_number=1, instruction="Toss the beef in the soy sauce and garlic and let stand for 10 minutes.", recipe_id=10))
    seedArray.append(Direction(step_number=2, instruction="Heat the oil in a skillet.", recipe_id=10))
    seedArray.append(Direction(step_number=3, instruction="Cook meat in oil until browned. If not tender, cover and cook 30-40 minutes on low heat.", recipe_id=10))
    seedArray.append(Direction(step_number=4, instruction="Turn up heat and add onion and peppers. Stir fry.", recipe_id=10))
    seedArray.append(Direction(step_number=5, instruction="Make sauce:  Mix cornstarch with one cup of water.  Add to pan and cook until thickened.  Add chopped tomatoes if desired.", recipe_id=10))
    seedArray.append(Direction(step_number=6, instruction="Serve hot on cooked rice or noodles.", recipe_id=10))
    seedArray.append(Direction(step_number=1, instruction="Heat the olive oil in a large, heavy pot.", recipe_id=11))
    seedArray.append(Direction(step_number=2, instruction="Add the onions, garlic and seasonings; cook until soft, about 5 minutes", recipe_id=11))
    seedArray.append(Direction(step_number=3, instruction="Add the rest of the ingredients.", recipe_id=11))
    seedArray.append(Direction(step_number=4, instruction="Ready to use, can or freeze!", recipe_id=11))
    seedArray.append(Direction(step_number=1, instruction="Cream sugar & lard. Add eggs.", recipe_id=12))
    seedArray.append(Direction(step_number=2, instruction="Put soda in sour milk and add.", recipe_id=12))
    seedArray.append(Direction(step_number=3, instruction="Add flour before stirring.", recipe_id=12))
    seedArray.append(Direction(step_number=4, instruction="Add salt and spices. Mix.", recipe_id=12))
    seedArray.append(Direction(step_number=5, instruction="Bake at 350 F for 45 minutes, or until a toothpick inserted in the middle comes out clean.", recipe_id=12))
    seedArray.append(Direction(step_number=1, instruction="Fry bacon with onion.", recipe_id=13))
    seedArray.append(Direction(step_number=2, instruction="Mix vinegar, water, and sugar in a small saucepan and boil for two minutes.", recipe_id=13))
    seedArray.append(Direction(step_number=3, instruction="Mix potatoes, eggs, parsley, and pepper in a large bowl. Transfer mixture to a casserole dish.", recipe_id=13))
    seedArray.append(Direction(step_number=4, instruction="Pour sauce over the potato mixture. Sprinkle with cheese and bake at 375 F for 20 minutes.", recipe_id=13))
    seedArray.append(Direction(step_number=1, instruction="Break up/cut up a head of cauliflower and broccoli on a large sheet pan with edges, sprayed with cooking spray.  ", recipe_id=14))
    seedArray.append(Direction(step_number=2, instruction="Drizzle with ¼ cup olive oil, 2 tablespoons lemon juice and 1 tablespoon minced garlic.", recipe_id=14))
    seedArray.append(Direction(step_number=3, instruction="Roast in oven at 375 for one hour, stirring occasionally, until tender and browned.", recipe_id=14))
    seedArray.append(Direction(step_number=1, instruction="Mix ingredients together.", recipe_id=15))
    seedArray.append(Direction(step_number=2, instruction="Shape into balls. These balls can be dipped into melted chocolate to make buckeyes for the holidays.", recipe_id=15))
    seedArray.append(Direction(step_number=3, instruction="Refrigerate until eaten.", recipe_id=15))
    seedArray.append(Direction(step_number=1, instruction="Melt butter. Mix in sugars.", recipe_id=16))
    seedArray.append(Direction(step_number=2, instruction="Add molasses. Mix well.", recipe_id=16))
    seedArray.append(Direction(step_number=3, instruction="Stir in sour milk.", recipe_id=16))
    seedArray.append(Direction(step_number=4, instruction="Add dry ingredients, stir well.", recipe_id=16))
    seedArray.append(Direction(step_number=5, instruction="Add raisins if desired.", recipe_id=16))
    seedArray.append(Direction(step_number=6, instruction="Make a test cookie. If it is too flat, add ½ cup of flour and try another test.", recipe_id=16))
    seedArray.append(Direction(step_number=7, instruction="Scoop and bake on a greased cookie sheet for 7-8 minutes. Cookies are firm but not crispy when done.", recipe_id=16))
    seedArray.append(Direction(step_number=1, instruction="Sift dry ingredients", recipe_id=17))
    seedArray.append(Direction(step_number=2, instruction="Cut in shortening, and then gradually stir in milk to make soft sticky dough.", recipe_id=17))
    seedArray.append(Direction(step_number=3, instruction="Knead on lightly floured board till smooth.", recipe_id=17))
    seedArray.append(Direction(step_number=4, instruction="Roll out ¼ to ½” thick.", recipe_id=17))
    seedArray.append(Direction(step_number=5, instruction="Bake on ungreased sheet - 450F 6-7 min. and then freeze, or finish baking another 6-8 minutes", recipe_id=17))
    seedArray.append(Direction(step_number=1, instruction="Preheat oven to 350 F and grease a loaf pan.", recipe_id=18))
    seedArray.append(Direction(step_number=2, instruction="Mash the ripe bananas with a fork.", recipe_id=18))
    seedArray.append(Direction(step_number=3, instruction="Combine the shortening and sugar. Add in eggs.", recipe_id=18))
    seedArray.append(Direction(step_number=4, instruction="Sift together the dry ingredients and stir into the liquid mixture. Add nuts, if desired.", recipe_id=18))
    seedArray.append(Direction(step_number=5, instruction="Pour batter into greased loaf pan and bake for 50 minutes to an hour, or until inserted toothpick comes out clean.", recipe_id=18))
    seedArray.append(Direction(step_number=6, instruction="Allow to cool in pan for a few minutes and then let cool completely before serving.", recipe_id=18))
    seedArray.append(Direction(step_number=1, instruction="Slice the very top of the bread and hollow out the loaf, reserving the removed bread pieces.", recipe_id=19))
    seedArray.append(Direction(step_number=2, instruction="Combine all dip ingredients and transfer to the hollowed-out loaf.", recipe_id=19))
    seedArray.append(Direction(step_number=3, instruction="Serve with the bread pieces for dipping.", recipe_id=19))
    seedArray.append(Direction(step_number=1, instruction="Preheat oven to 350 F and grease a loaf pan.", recipe_id=20))
    seedArray.append(Direction(step_number=2, instruction="Place diced rhubarb in an 11x7x1.5 inch pan", recipe_id=20))
    seedArray.append(Direction(step_number=3, instruction="In a small saucepan, mix the sugar, cornstarch or tapioca, water, and vanilla and cook until clear and thick. Pour over the rhubarb.", recipe_id=20))
    seedArray.append(Direction(step_number=4, instruction="Combine the flour, brown sugar, quick cooking oatmeal, cinnamon, and melted butter and sprinkle over the rhubarb and sauce.", recipe_id=20))
    seedArray.append(Direction(step_number=5, instruction="Bake at 350 F for 40-50 minutes.", recipe_id=20))

    for item in seedArray:
        db.session.add(item)

    db.session.commit()

def undo_directions():
    db.session.execute('TRUNCATE directions RESTART IDENTITY CASCADE;')
    db.session.commit()
