from app.models import db, Ingredient

def seed_ingredients():
    seedArray = []

    seedArray.append(Ingredient(amt=1, measurement="cup", ingredient_name="sugar", recipe_id=1))
    seedArray.append(Ingredient(amt=1, measurement="cup", ingredient_name="molasses", recipe_id=1))
    seedArray.append(Ingredient(amt=1, measurement="cup", ingredient_name="butter (lard)", recipe_id=1))
    seedArray.append(Ingredient(amt=0.5, measurement="cup", ingredient_name="hot water", recipe_id=1))
    seedArray.append(Ingredient(amt=1, measurement="tablespoon", ingredient_name="baking soda", recipe_id=1))
    seedArray.append(Ingredient(amt=2, ingredient_name="eggs", recipe_id=1))
    seedArray.append(Ingredient(amt=2, measurement="teaspoons", ingredient_name="cinnamon", recipe_id=1))
    seedArray.append(Ingredient(amt=1, measurement="teaspoon", ingredient_name="ginger", recipe_id=1))
    seedArray.append(Ingredient(amt=5, measurement="cups", ingredient_name="flour", recipe_id=1))
    seedArray.append(Ingredient(amt=0.5, measurement="teaspoon", ingredient_name="baking powder", recipe_id=1))
    seedArray.append(Ingredient(amt=1, measurement="cup", ingredient_name="butter, melted", recipe_id=2))
    seedArray.append(Ingredient(amt=1, measurement="cup", ingredient_name="packed Splenda + brown sugar blend (or 1 .75 cups regular brown sugar)", recipe_id=2))
    seedArray.append(Ingredient(amt=2, ingredient_name="eggs", recipe_id=2))
    seedArray.append(Ingredient(amt=2, measurement="teaspoons", ingredient_name="vanilla", recipe_id=2))
    seedArray.append(Ingredient(amt=2, measurement="cups", ingredient_name="old fashioned oats", recipe_id=2))
    seedArray.append(Ingredient(amt=2, measurement="cups", ingredient_name="flour", recipe_id=2))
    seedArray.append(Ingredient(amt=1, measurement="teaspoon", ingredient_name="baking soda", recipe_id=2))
    seedArray.append(Ingredient(amt=2, measurement="cups", ingredient_name="chocolate chips", recipe_id=2))
    seedArray.append(Ingredient(amt=1, measurement="head", ingredient_name="shredded lettuce", recipe_id=3))
    seedArray.append(Ingredient(amt=0.5, measurement="cup", ingredient_name="chopped celery", recipe_id=3))
    seedArray.append(Ingredient(amt=0.5, measurement="cup", ingredient_name="chopped green peppers", recipe_id=3))
    seedArray.append(Ingredient(amt=0.25, measurement="cup", ingredient_name="chopped Spanish olives", recipe_id=3))
    seedArray.append(Ingredient(amt=1, measurement="package", ingredient_name="cooked peas", recipe_id=3))
    seedArray.append(Ingredient(amt=1, measurement="pint", ingredient_name="real mayonnaise sprinkled with 2 tablespoons of sugar", recipe_id=3))
    seedArray.append(Ingredient(amt=4, measurement="ounces", ingredient_name="grated cheddar cheese", recipe_id=3))
    seedArray.append(Ingredient(amt=1, ingredient_name="egg", recipe_id=4))
    seedArray.append(Ingredient(amt=0.75, measurement="cup", ingredient_name="milk", recipe_id=4))
    seedArray.append(Ingredient(amt=0.5, measurement="cup", ingredient_name="vegetable oil", recipe_id=4))
    seedArray.append(Ingredient(amt=2, measurement="cups", ingredient_name="flour", recipe_id=4))
    seedArray.append(Ingredient(amt=0.3, measurement="cup", ingredient_name="sugar", recipe_id=4))
    seedArray.append(Ingredient(amt=3, measurement="teaspoons", ingredient_name="baking powder", recipe_id=4))
    seedArray.append(Ingredient(amt=1, measurement="teaspoon", ingredient_name="salt", recipe_id=4))
    seedArray.append(Ingredient(amt=1, measurement="cup", ingredient_name="blueberries", recipe_id=4))
    seedArray.append(Ingredient(amt=1, measurement="cup", ingredient_name="fried, cubed bacon", recipe_id=5))
    seedArray.append(Ingredient(amt=1, measurement="cup", ingredient_name="thinly-sliced onions", recipe_id=5))
    seedArray.append(Ingredient(amt=1, measurement="quart", ingredient_name="water", recipe_id=5))
    seedArray.append(Ingredient(amt=1, measurement="quart", ingredient_name="diced potatoes", recipe_id=5))
    seedArray.append(Ingredient(amt=1, measurement="can", ingredient_name="whole kernel corn", recipe_id=5))
    seedArray.append(Ingredient(amt=2, measurement="cans", ingredient_name="cream style corn", recipe_id=5))
    seedArray.append(Ingredient(amt=1.5, measurement="quarts", ingredient_name="milk", recipe_id=5))
    seedArray.append(Ingredient(amt=6, measurement="tablespoons", ingredient_name="flour", recipe_id=5))
    seedArray.append(Ingredient(amt=1, measurement="can", ingredient_name="evaporated milk", recipe_id=5))
    seedArray.append(Ingredient(amt=2, measurement="tablespoons", ingredient_name="salt", recipe_id=5))
    seedArray.append(Ingredient(amt=0.5, measurement="teaspoon", ingredient_name="pepper", recipe_id=5))
    seedArray.append(Ingredient(amt=6, ingredient_name="tart apples (or two cans/five cups sliced pie apples, drained)", recipe_id=6))
    seedArray.append(Ingredient(amt=1, ingredient_name="nine-inch unbaked pastry shell", recipe_id=6))
    seedArray.append(Ingredient(amt=0.5, measurement="cup", ingredient_name="sugar", recipe_id=6))
    seedArray.append(Ingredient(amt=0.75, measurement="cup", ingredient_name="enriched flour", recipe_id=6))
    seedArray.append(Ingredient(amt=5, measurement="tablespoons", ingredient_name="butter", recipe_id=6))
    seedArray.append(Ingredient(amt=30, measurement="ounces", ingredient_name="mayonnaise", recipe_id=7))
    seedArray.append(Ingredient(amt=4, measurement="cups", ingredient_name="chopped onions", recipe_id=7))
    seedArray.append(Ingredient(amt=4, measurement="cups", ingredient_name="shredded sharp cheese", recipe_id=7))
    seedArray.append(Ingredient(amt=0.5, measurement="cup", ingredient_name="parmesan cheese (optional)", recipe_id=7))
    seedArray.append(Ingredient(amt=0.25, measurement="cup", ingredient_name="chopped fresh parsley (optional)", recipe_id=7))
    seedArray.append(Ingredient(amt=1, measurement="package", ingredient_name="instant pistachio pudding mix", recipe_id=8))
    seedArray.append(Ingredient(amt=1, measurement="can", ingredient_name="pineapple; drain well and reserve .5 cup of juice for liquid", recipe_id=8))
    seedArray.append(Ingredient(amt=1, measurement="package", ingredient_name="Cool Whip", recipe_id=8))
    seedArray.append(Ingredient(amt=0.5, measurement="cup", ingredient_name="small marshmallows", recipe_id=8))
    seedArray.append(Ingredient(amt=0.5, measurement="cup", ingredient_name="nut meats, chopped", recipe_id=8))
    seedArray.append(Ingredient(amt=10, ingredient_name="maraschino cherries, quartered", recipe_id=8))
    seedArray.append(Ingredient(amt=3, measurement="cups", ingredient_name="potatoes, shredded", recipe_id=9))
    seedArray.append(Ingredient(amt=1.5, measurement="tablespoons", ingredient_name="flour", recipe_id=9))
    seedArray.append(Ingredient(amt=2, ingredient_name="egg", recipe_id=9))
    seedArray.append(Ingredient(amt=1, measurement="tablespoon", ingredient_name="onion", recipe_id=9))
    seedArray.append(Ingredient(amt=0.5, measurement="teaspoon", ingredient_name="baking powder", recipe_id=9))
    seedArray.append(Ingredient(amt=1, measurement="pound", ingredient_name="beef chuck or round, sliced thinly", recipe_id=10))
    seedArray.append(Ingredient(amt=0.25, measurement="cup", ingredient_name="soy sauce", recipe_id=10))
    seedArray.append(Ingredient(amt=1, measurement="clove", ingredient_name="garlic", recipe_id=10))
    seedArray.append(Ingredient(amt=0.25, measurement="cup", ingredient_name="salad oil", recipe_id=10))
    seedArray.append(Ingredient(amt=1, measurement="cup", ingredient_name="green onion, thinly sliced", recipe_id=10))
    seedArray.append(Ingredient(amt=1, measurement="cup", ingredient_name="green or red bell pepper, sliced or diced", recipe_id=10))
    seedArray.append(Ingredient(amt=1, measurement="tablespoon", ingredient_name="corn starch", recipe_id=10))
    seedArray.append(Ingredient(amt=1, measurement="cup", ingredient_name="water", recipe_id=10))
    seedArray.append(Ingredient(amt=2, ingredient_name="chopped tomatoes", recipe_id=10))
    seedArray.append(Ingredient(amt=2, measurement="tablespoons", ingredient_name="olive oil", recipe_id=11))
    seedArray.append(Ingredient(amt=1.5, measurement="cups", ingredient_name="chopped onion ", recipe_id=11))
    seedArray.append(Ingredient(amt=4, measurement="cloves", ingredient_name="garlic", recipe_id=11))
    seedArray.append(Ingredient(amt=1, measurement="teaspoon", ingredient_name="black pepper", recipe_id=11))
    seedArray.append(Ingredient(amt=1, measurement="tablespoon", ingredient_name="Italian seasoning", recipe_id=11))
    seedArray.append(Ingredient(amt=0.25, measurement="cup", ingredient_name="sugar", recipe_id=11))
    seedArray.append(Ingredient(amt=1, measurement="can", ingredient_name="tomato paste (6 oz)", recipe_id=11))
    seedArray.append(Ingredient(amt=3, measurement="cans", ingredient_name="crushed tomatoes (28 oz. each)", recipe_id=11))
    seedArray.append(Ingredient(amt=1, measurement="can", ingredient_name="diced tomatoes (28 oz.)", recipe_id=11))
    seedArray.append(Ingredient(amt=0.5, measurement="cup", ingredient_name="grated Parmesan cheese", recipe_id=11))
    seedArray.append(Ingredient(amt=1, measurement="cup", ingredient_name="water", recipe_id=11))
    seedArray.append(Ingredient(ingredient_name="salt, to taste", recipe_id=11))
    seedArray.append(Ingredient(amt=1.5, measurement="cups", ingredient_name="sugar", recipe_id=12))
    seedArray.append(Ingredient(amt=0.5, measurement="cup", ingredient_name="lard", recipe_id=12))
    seedArray.append(Ingredient(amt=2, ingredient_name="eggs", recipe_id=12))
    seedArray.append(Ingredient(amt=1, measurement="cup", ingredient_name="sour milk", recipe_id=12))
    seedArray.append(Ingredient(amt=1.5, measurement="cups", ingredient_name="flour", recipe_id=12))
    seedArray.append(Ingredient(amt=2, measurement="teaspoons", ingredient_name="cinnamon", recipe_id=12))
    seedArray.append(Ingredient(amt=1, measurement="teaspoon", ingredient_name="cloves", recipe_id=12))
    seedArray.append(Ingredient(amt=1, measurement="teaspoon", ingredient_name="nutmeg", recipe_id=12))
    seedArray.append(Ingredient(amt=1, measurement="teaspoon", ingredient_name="salt", recipe_id=12))
    seedArray.append(Ingredient(amt=1, measurement="teaspoon", ingredient_name="baking soda", recipe_id=12))
    seedArray.append(Ingredient(amt=1, measurement="teaspoon", ingredient_name="baking powder", recipe_id=12))
    seedArray.append(Ingredient(amt=1, measurement="pound", ingredient_name="bacon", recipe_id=13))
    seedArray.append(Ingredient(amt=0.5, measurement="cup", ingredient_name="chopped onions", recipe_id=13))
    seedArray.append(Ingredient(amt=0.25, measurement="cup", ingredient_name="vinegar", recipe_id=13))
    seedArray.append(Ingredient(amt=2, measurement="tablespoons", ingredient_name="water", recipe_id=13))
    seedArray.append(Ingredient(amt=3, measurement="tablespoons", ingredient_name="sugar", recipe_id=13))
    seedArray.append(Ingredient(amt=3, measurement="cups", ingredient_name="potatoes, cooked and cubed", recipe_id=13))
    seedArray.append(Ingredient(amt=2, ingredient_name="hard-boiled eggs", recipe_id=13))
    seedArray.append(Ingredient(amt=2, measurement="tablespoons", ingredient_name="parsley", recipe_id=13))
    seedArray.append(Ingredient(ingredient_name="pepper, to taste", recipe_id=13))
    seedArray.append(Ingredient(amt=1, measurement="cup", ingredient_name="shredded cheddar cheese", recipe_id=13))
    seedArray.append(Ingredient(amt=1, measurement="head", ingredient_name="cauliflower", recipe_id=14))
    seedArray.append(Ingredient(amt=1, measurement="head", ingredient_name="broccoli", recipe_id=14))
    seedArray.append(Ingredient(amt=0.25, measurement="cup", ingredient_name="olive oil", recipe_id=14))
    seedArray.append(Ingredient(amt=2, measurement="tablespoons", ingredient_name="lemon juice", recipe_id=14))
    seedArray.append(Ingredient(amt=1, measurement="tablespoon", ingredient_name="minced garlic", recipe_id=14))
    seedArray.append(Ingredient(amt=1.5, measurement="cups", ingredient_name="peanut butter", recipe_id=15))
    seedArray.append(Ingredient(amt=2, measurement="cups", ingredient_name="powdered sugar ", recipe_id=15))
    seedArray.append(Ingredient(amt=1, measurement="teaspoon", ingredient_name="vanilla", recipe_id=15))
    seedArray.append(Ingredient(amt=2, measurement="tablespoons", ingredient_name="milk", recipe_id=15))
    seedArray.append(Ingredient(amt=1, measurement="cup", ingredient_name="softened or melted butter", recipe_id=16))
    seedArray.append(Ingredient(amt=0.5, measurement="cup", ingredient_name="brown sugar", recipe_id=16))
    seedArray.append(Ingredient(amt=0.5, measurement="cup", ingredient_name="sugar", recipe_id=16))
    seedArray.append(Ingredient(amt=1, measurement="cup", ingredient_name="molasses", recipe_id=16))
    seedArray.append(Ingredient(amt=1, measurement="cup", ingredient_name="sour milk", recipe_id=16))
    seedArray.append(Ingredient(amt=2, measurement="teaspoons", ingredient_name="baking soda", recipe_id=16))
    seedArray.append(Ingredient(amt=2, measurement="teaspoons", ingredient_name="cinnamon", recipe_id=16))
    seedArray.append(Ingredient(amt=0.25, measurement="teaspoon", ingredient_name="salt", recipe_id=16))
    seedArray.append(Ingredient(amt=4.5, measurement="cups", ingredient_name="flour (or more)", recipe_id=16))
    seedArray.append(Ingredient(amt=1.5, measurement="cups", ingredient_name="raisins (optional)", recipe_id=16))
    seedArray.append(Ingredient(amt=12, measurement="cups", ingredient_name="all-purpose flour", recipe_id=17))
    seedArray.append(Ingredient(amt=2, measurement="tablespoons", ingredient_name="salt", recipe_id=17))
    seedArray.append(Ingredient(amt=5, measurement="tablespoons", ingredient_name="baking powder", recipe_id=17))
    seedArray.append(Ingredient(amt=1.5, measurement="cup", ingredient_name="shortening", recipe_id=17))
    seedArray.append(Ingredient(amt=4, measurement="cups", ingredient_name="milk", recipe_id=17))
    seedArray.append(Ingredient(amt=3, ingredient_name="bananas, mashed", recipe_id=18))
    seedArray.append(Ingredient(amt=1, measurement="cup", ingredient_name="sugar", recipe_id=18))
    seedArray.append(Ingredient(amt=0.5, measurement="cup", ingredient_name="shortening", recipe_id=18))
    seedArray.append(Ingredient(amt=2, ingredient_name="eggs", recipe_id=18))
    seedArray.append(Ingredient(amt=2, measurement="cups", ingredient_name="flour", recipe_id=18))
    seedArray.append(Ingredient(amt=1, measurement="teaspoon", ingredient_name="baking soda", recipe_id=18))
    seedArray.append(Ingredient(amt=0.5, measurement="teaspoon", ingredient_name="salt", recipe_id=18))
    seedArray.append(Ingredient(amt=0.25, measurement="cup", ingredient_name="nuts", recipe_id=18))
    seedArray.append(Ingredient(amt=2, measurement="pounds", ingredient_name="pumpernickel loaf", recipe_id=19))
    seedArray.append(Ingredient(amt=1, measurement="pint", ingredient_name="sour cream", recipe_id=19))
    seedArray.append(Ingredient(amt=1, measurement="pint", ingredient_name="salad dressings", recipe_id=19))
    seedArray.append(Ingredient(amt=1, measurement="package", ingredient_name="chipped beef", recipe_id=19))
    seedArray.append(Ingredient(amt=2, measurement="tablespoons", ingredient_name="minced onion", recipe_id=19))
    seedArray.append(Ingredient(amt=2, measurement="tablespoons", ingredient_name="dill weed", recipe_id=19))
    seedArray.append(Ingredient(amt=2, measurement="tablespoons", ingredient_name="parsley", recipe_id=19))
    seedArray.append(Ingredient(amt=4, measurement="cups", ingredient_name="finely diced rhubarb", recipe_id=20))
    seedArray.append(Ingredient(amt=0.75, measurement="cup", ingredient_name="sugar", recipe_id=20))
    seedArray.append(Ingredient(amt=2, measurement="tablespoons", ingredient_name="cornstarch or quick-cooking tapioca", recipe_id=20))
    seedArray.append(Ingredient(amt=1, measurement="cup", ingredient_name="water", recipe_id=20))
    seedArray.append(Ingredient(amt=1, measurement="teaspoon", ingredient_name="vanilla", recipe_id=20))
    seedArray.append(Ingredient(amt=1, measurement="cup", ingredient_name="flour", recipe_id=20))
    seedArray.append(Ingredient(amt=1, measurement="cup", ingredient_name="brown sugar", recipe_id=20))
    seedArray.append(Ingredient(amt=0.75, measurement="cup", ingredient_name="quick cooking oatmeal", recipe_id=20))
    seedArray.append(Ingredient(amt=0.5, measurement="cup", ingredient_name="melted butter", recipe_id=20))
    seedArray.append(Ingredient(amt=1, measurement="teaspoon", ingredient_name="cinnamon", recipe_id=20))

    for item in seedArray:
        db.session.add(item)

    db.session.commit()

def undo_ingredients():
    db.session.execute('TRUNCATE ingredients RESTART IDENTITY CASCADE;')
    db.session.commit()
