"""empty message

Revision ID: 90817cebc10c
Revises: dbc141c2c620
Create Date: 2021-09-01 21:47:24.215121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90817cebc10c'
down_revision = 'dbc141c2c620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('directions', 'step_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('directions', 'step_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
